apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qrce-ingress
  namespace: qrce
spec:
  rules:
    - host: qrce.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qrce-platform
                port:
                  number: 80
