apiVersion: apps/v1
kind: Deployment
metadata:
  name: qrce-platform
spec:
  replicas: {{ .Values.platform.replicas }}
  selector:
    matchLabels:
      app: qrce-platform
  template:
    metadata:
      labels:
        app: qrce-platform
    spec:
      containers:
        - name: platform
          image: {{ .Values.platform.image }}:{{ .Values.platform.tag }}
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "{{ .Values.platform.resources.requests.memory }}"
              cpu: "{{ .Values.platform.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.platform.resources.limits.memory }}"
              cpu: "{{ .Values.platform.resources.limits.cpu }}"

