apiVersion: apps/v1
kind: Deployment
metadata:
  name: qrce-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: qrce-worker
  template:
    metadata:
      labels:
        app: qrce-worker
    spec:
      containers:
        - name: worker
          image: qrce-worker:latest
